services:
  banking-service:
    image: joao0212/banking-service:v2
    container_name: banking-service-container
    environment:
      - VALIDATION_HOST=host.docker.internal
      - VALIDATION_PORT=8181
      - DB_USER=joao
      - DB_PASS=joao
      - DB_HOST_HOST=postgres-db-alura-banking-service
      - DB_PORT=5432
    ports:
      - 8080:8080
    depends_on:
      - postgres-db-alura-banking-service

  postgres-db-alura-banking-service:
    image: postgres:14
    container_name: postgres-db-alura-banking-service-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banking_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local